### ISSUE TITLE
"Invalid email or password"

### ISSUE THREAD

**Issue by Trevor-Salespad** [PayFabric/Release-Notes#3]
We're having multiple customers reporting issues using Payfabric.
![image](https://user-images.githubusercontent.com/81307342/112312273-035a9200-8c7d-11eb-84f9-f9d8ba05b5c2.png)

![image](https://user-images.githubusercontent.com/81307342/112312323-13727180-8c7d-11eb-9b56-89422c4494b9.png)

**Comment by JingjingHu** [comment]
Please report issues to support@payfabric.com, thanks.
